In [1]:
import torch

In [2]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [11]:
#TENSOR.shape
#for i in range(3):
#    print(TENSOR[0,i,:])
    
#for i in range(3):
#    print(TENSOR[0,:,i])    
    
print(TENSOR[-1,-2,:])    

tensor([3, 6, 9])


In [12]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.1395, 0.1668, 0.6781, 0.2610],
         [0.5577, 0.5371, 0.7747, 0.1158],
         [0.8357, 0.8159, 0.5073, 0.8669]]),
 torch.float32)

In [13]:
# image shape tensor
random_image_tensor = torch.rand(size = (224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
# Get a tensor containing range of numbers
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Can also create a tensor of zeros similar to another tensor
zero_tensor = torch.zeros_like(zero_to_ten)
zero_tensor.shape, zero_to_ten.shape

(torch.Size([10]), torch.Size([10]))

In [17]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # default float32
                               device=None, # default CPU
                               requires_grad=False) # if true records ops on tensor
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [18]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

##### Getting info about a Tensor

In [19]:
some_tensor = torch.rand(size=(3,4))
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Device : {some_tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device : cpu


### Matrix Multiplication (is all you need)

The main two rules for matrix multiplication to remember are:
1- The inner dimensions must match:
- (3,2) @ (3,2) will not work
- (2,3) @ (3,2) will work
- (3,2) @ (2,3) will work

2- The resulting matrix has the shape of outer dimensions:
- (2,3) @ (3,2) -> (2,2)
- (3,2) @ (2,3) -> (3,3)

In [20]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [4]:
#If the first argument is 1-dimensional and the second argument 
# is 2-dimensional, a 1 is prepended to its dimension
v1= torch.tensor([3,3,3])
print(f'v1 shape is : {v1.shape}')
mat1 = torch.tensor([[2,2,1],
                     [1,1,1],
                     [2,1,1]])
print(f'Mat1 shape is : {mat1.shape}')
tmp = torch.matmul(v1,mat1)
tmp, tmp.shape

v1 shape is : torch.Size([3])
Mat1 shape is : torch.Size([3, 3])


(tensor([15, 12,  9]), torch.Size([3]))

In [28]:
tmp = torch.matmul(mat1,v1)
tmp, tmp.shape

(tensor([15,  9, 12]), torch.Size([3]))

https://pytorch.org/docs/stable/generated/torch.matmul.html

In [1]:
import torch
my_nd_matrix = torch.rand(size= (2,3,16,16))
my_2d_matrix = torch.rand(size=(1,16,16))
print(my_nd_matrix.shape)

torch.Size([2, 3, 16, 16])


In [17]:
tmp = torch.matmul(my_nd_matrix, my_2d_matrix)
print(tmp.shape)

torch.Size([2, 3, 16, 16])


In [2]:
torch.manual_seed(42)
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)
print(f'input shape: {x.shape}')
print(f'output : {output} \n\n output shape: {output.shape}')


input shape: torch.Size([3, 2])
output : tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward>) 

 output shape: torch.Size([3, 6])


In [3]:
linear = torch.nn.Linear(in_features=3, out_features=6)
x = tensor_A.T
output = linear(x)
print(f'input shape: {x.shape}')
print(f'output : {output} \n\n output shape: {output.shape}')

input shape: torch.Size([2, 3])
output : tensor([[-1.0681,  1.6103, -2.0063, -3.2169,  1.4339,  1.1610],
        [-1.4565,  1.6911, -2.8912, -4.0798,  1.9106,  1.4264]],
       grad_fn=<AddmmBackward>) 

 output shape: torch.Size([2, 6])


#### Finding the min, max, mean, sum etc (aggregation)

In [4]:
x = torch.arange(0,100,10)

In [6]:
print(f'Min: {x.min()} \n Max: {x.max()} \n Mean: {x.type(torch.float32).mean()} \n Sum: {x.sum()}  ')
#torch.mean() requires values to b in float.

Min: 0 
 Max: 90 
 Mean: 45.0 
 Sum: 450  


In [7]:
mytensor = torch.arange(10,100,10)
print(f'Tensor: {mytensor}')
# Returns index of max and min values
print(f"Index where max value occurs: {mytensor.argmax()}")
print(f"Index where min value occurs: {mytensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [8]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [9]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

#### Reshaping, stacking, squeezing, unsqueezing

In [10]:
x = torch.arange(1., 8.).type(torch.float32)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [11]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [12]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [13]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [14]:
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [16]:
x_hstack = torch.stack([x,x], dim=1)
x_hstack, x_hstack.shape

(tensor([[5., 5.],
         [2., 2.],
         [3., 3.],
         [4., 4.],
         [5., 5.],
         [6., 6.],
         [7., 7.]]),
 torch.Size([7, 2]))

In [17]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [18]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [19]:
x_orig = torch.rand(size = (224,224,3))
x_permuted = x_orig.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [20]:
x = torch.arange(1,10).reshape(1,3,-1)
x.shape, x

(torch.Size([1, 3, 3]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [24]:
# Let's index bracket by bracket
print(f"First square bracket:\n {x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [25]:
# Get values of 0th dimension and the 0 index of 1st dimension
x[:, 0]


tensor([[1, 2, 3]])

In [28]:
x[0,:,2]

tensor([3, 6, 9])

In [29]:
# Get all vals of 0th & 1st dim but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [30]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [31]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [1]:
import torch
import random
rand_seed = 42
torch.manual_seed(seed=rand_seed)
random_tensor_C = torch.rand(3,4)

#Have to reset seed everytime otherwise next tensor will be different
torch.random.manual_seed(seed=rand_seed)
random_tensor_D = torch.rand(3,4)

print(f'Tensor C: \n {random_tensor_C}')
print(f'Tensor C: \n {random_tensor_D}')
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor C: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [2]:
torch.cuda.is_available()

True

In [3]:
device= 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [5]:
tensor = torch.tensor([1,2,3])
print (tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [6]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)